yolo:
  model_path: yolo_det_rpi/yolov8n.onnx
  confidence_threshold: 0.5
  nms_threshold: 0.45
  target_labels:
    - person
  detections_required: 2
  inference_interval_seconds: 1
  server_port: 5555

camera:
  device: 0
  width: 1920
  height: 1080
  fps: 30
  use_picamera2: true
  queue_size: 5
  circular_buffer_duration_sec: 60
  resize_width: 640
  resize_height: 480
  h264_bitrate: 20000000

recording:
  video_dir: videos
  video_extension: .mp4
  retention_days: 14

web:
  host: 0.0.0.0
  port: 8000
  debug: false
